/// <reference lib="webworker" />

import { compressImageData, compressPngFile } from "../codecs/compress";
import { buildOutputName } from "../utils/filenames";
import {
  formatFromFile,
  outputExtension,
  resolveOutputFormat,
} from "../utils/format";
import type {
  CompressionStrategy,
  OutputFormat,
  WorkerCompressRequest,
  WorkerCompressResponse,
  WorkerProgressStage,
  WorkerRuntimeIssue,
} from "../utils/types";

const MAX_IMAGE_DATA_PIXELS = 12_000_000;

function postProgress(
  sourceId: string,
  variantId: string,
  progress: number,
  stage: WorkerProgressStage
) {
  const message: WorkerCompressResponse = {
    kind: "progress",
    progress,
    sourceId,
    stage,
    variantId,
  };
  self.postMessage(message);
}

function mimeTypeForFormat(format: OutputFormat) {
  if (format === "png") {
    return "image/png";
  }

  if (format === "webp") {
    return "image/webp";
  }

  if (format === "avif") {
    return "image/avif";
  }

  return "image/jpeg";
}

function postRuntimeIssue(
  error: string,
  detail?: string,
  sourceId?: string,
  variantId?: string
) {
  const message: WorkerRuntimeIssue = {
    detail,
    error,
    kind: "runtime-error",
    sourceId,
    variantId,
  };

  self.postMessage(message);
}

function bitmapToImageData(bitmap: ImageBitmap): ImageData {
  const canvas = new OffscreenCanvas(bitmap.width, bitmap.height);
  const ctx = canvas.getContext("2d");
  if (!ctx) {
    throw new Error("Failed to initialize canvas context in worker.");
  }

  ctx.drawImage(bitmap, 0, 0);
  const imageData = ctx.getImageData(0, 0, bitmap.width, bitmap.height);
  return imageData;
}

function qualityForCanvasEncode(
  format: OutputFormat,
  settings: WorkerCompressRequest["settings"],
  strategy: CompressionStrategy
) {
  if (format === "png") {
    return undefined;
  }

  if (strategy === "webp-lossless" || settings.lossless) {
    return 1;
  }

  return Math.max(0.1, Math.min(1, settings.quality / 100));
}

async function encodeWithCanvas(
  bitmap: ImageBitmap,
  outputFormat: OutputFormat,
  settings: WorkerCompressRequest["settings"],
  strategy: CompressionStrategy
): Promise<ArrayBuffer> {
  const canvas = new OffscreenCanvas(bitmap.width, bitmap.height);
  const ctx = canvas.getContext("2d");

  if (!ctx) {
    throw new Error("Failed to initialize canvas context in worker.");
  }

  ctx.drawImage(bitmap, 0, 0);
  bitmap.close();

  const quality = qualityForCanvasEncode(outputFormat, settings, strategy);
  const blob = await canvas.convertToBlob({
    type: mimeTypeForFormat(outputFormat),
    ...(quality === undefined ? {} : { quality }),
  });

  canvas.width = 0;
  canvas.height = 0;

  return blob.arrayBuffer();
}

async function encodeForStrategy(
  file: File,
  settings: WorkerCompressRequest["settings"],
  strategy: CompressionStrategy
) {
  const outputFormat = resolveOutputFormat(file, settings.format);
  const sourceFormat = formatFromFile(file);
  let note: string | undefined;

  if (strategy === "png-optimize" && sourceFormat === "png") {
    try {
      const bytesBuffer = await compressPngFile(file);
      return {
        bytesBuffer,
        note,
        outputFormat,
        outputStage: "encoding" as const,
      };
    } catch {
      note =
        "PNG optimization fell back to a PNG re-encode after the optimizer failed.";
    }
  }

  const bitmap = await createImageBitmap(file);
  const filePixels = bitmap.width * bitmap.height;
  const outputStage: WorkerProgressStage = "encoding";

  if (
    filePixels >= MAX_IMAGE_DATA_PIXELS &&
    (outputFormat === "webp" || outputFormat === "jpeg")
  ) {
    const bytesBuffer = await encodeWithCanvas(
      bitmap,
      outputFormat,
      settings,
      strategy
    );

    return { bytesBuffer, note, outputFormat, outputStage };
  }

  let imageData: ImageData;
  try {
    imageData = bitmapToImageData(bitmap);
  } finally {
    bitmap.close();
  }

  let bytesBuffer: ArrayBuffer;

  try {
    bytesBuffer = await compressImageData(
      imageData,
      {
        ...settings,
        format: outputFormat,
      },
      strategy
    );
  } catch (error) {
    if (strategy !== "png-quantized") {
      throw error;
    }

    note =
      "Smart PNG fell back to a lossless PNG export after quantization failed.";
    bytesBuffer = await compressImageData(
      imageData,
      {
        ...settings,
        format: "png",
        pngMode: "lossless",
      },
      "png-encode-fallback"
    );
  }

  return { bytesBuffer, note, outputFormat, outputStage };
}

self.onmessage = async (event: MessageEvent<WorkerCompressRequest>) => {
  const {
    autoGenerated = true,
    sourceId,
    sourceFormat,
    variantId,
    file,
    settings,
    strategy,
  } = event.data as WorkerCompressRequest & { autoGenerated?: boolean };

  try {
    postProgress(sourceId, variantId, 20, "decoding");
    const { bytesBuffer, note, outputFormat, outputStage } =
      await encodeForStrategy(file, settings, strategy);
    postProgress(sourceId, variantId, 90, outputStage);
    const requestedExtension = outputExtension(outputFormat);
    const outputName = buildOutputName(file.name, requestedExtension);
    const mime = mimeTypeForFormat(outputFormat);
    const output = new Blob([bytesBuffer], { type: mime });
    const message: WorkerCompressResponse = {
      autoGenerated,
      format: outputFormat,
      kind: "result",
      note,
      ok: true,
      output,
      outputName,
      sourceFormat,
      sourceId,
      strategy,
      variantId,
    };
    self.postMessage(message);
  } catch (error) {
    const message: WorkerCompressResponse = {
      error:
        error instanceof Error
          ? error.message
          : "Compression failed unexpectedly.",
      kind: "result",
      ok: false,
      sourceId,
      variantId,
    };
    self.postMessage(message);
  }
};

self.addEventListener("error", (event) => {
  postRuntimeIssue(
    event.message || "The compression worker crashed unexpectedly.",
    [
      event.filename ? `file: ${event.filename}` : null,
      event.lineno ? `line: ${event.lineno}` : null,
      event.colno ? `column: ${event.colno}` : null,
    ]
      .filter(Boolean)
      .join(", ") || undefined
  );
});

self.addEventListener("unhandledrejection", (event) => {
  const reason = event.reason;
  let error = "The compression worker hit an unhandled rejection.";

  if (reason instanceof Error) {
    error = reason.message;
  } else if (typeof reason === "string") {
    error = reason;
  }

  const detail =
    reason instanceof Error && reason.stack ? reason.stack : undefined;

  postRuntimeIssue(error, detail);
});
