import { zip } from "fflate";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { sanitizeFilename } from "../../lib/utils/filenames";
import {
  formatFromFile,
  resolveOutputFormat,
  settingsSignature,
} from "../../lib/utils/format";
import { presets } from "../../lib/utils/presets";
import {
  DEFAULT_QUALITY,
  loadSettings,
  saveSettings,
} from "../../lib/utils/storage";
import type {
  CompressionJob,
  CompressionJobStatus,
  CompressionSettings,
  CompressionStrategy,
  CompressionVariant,
  OutputFormat,
  WorkerCompressResponse,
} from "../../lib/utils/types";
import { CompressionList } from "./compression-list";
import { Dropzone } from "./dropzone";
import { ToolbarControls } from "./preset-controls";
import { PreviewPanel } from "./preview-panel";
import { SettingsDialog } from "./settings-dialog";

const defaultSettings: CompressionSettings = {
  format: "auto",
  quality: DEFAULT_QUALITY,
  lossless: false,
  pngColors: 256,
  pngMode: "lossless",
};

const genericWorkerFailureMessage =
  "The compression worker stopped before it could finish.";

function formatWorkerRuntimeIssue(
  error: string,
  detail?: string,
  context?: string
) {
  const parts = [error.trim()];

  if (context) {
    parts.push(`(${context})`);
  }

  if (detail?.trim()) {
    parts.push(detail.trim());
  }

  return parts.join(" ").trim();
}

function failProcessingJobs(
  current: CompressionJob[],
  error: string
): CompressionJob[] {
  return current.map((job) => ({
    ...job,
    error,
    status: job.status === "processing" ? "error" : job.status,
    variants: job.variants.map((variant) =>
      variant.status === "processing"
        ? {
            ...variant,
            error,
            progress: 100,
            status: "error" as const,
          }
        : variant
    ),
  }));
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

function uniqueName(original: string, used: Set<string>): string {
  const normalizedOriginal = sanitizeFilename(original, "image.jpg");

  if (!used.has(normalizedOriginal)) {
    used.add(normalizedOriginal);
    return normalizedOriginal;
  }

  const dotIndex = normalizedOriginal.lastIndexOf(".");
  const base =
    dotIndex > -1 ? normalizedOriginal.slice(0, dotIndex) : normalizedOriginal;
  const ext = dotIndex > -1 ? normalizedOriginal.slice(dotIndex) : "";

  let count = 1;
  while (used.has(`${base}-${count}${ext}`)) {
    count += 1;
  }

  const next = `${base}-${count}${ext}`;
  used.add(next);
  return next;
}

interface CompressionTask {
  // Set on the Safe + Smaller candidates emitted by Auto mode.
  auto?: boolean;
  autoGenerated: boolean;
  presetId: string | null;
  settings: CompressionSettings;
  strategy: CompressionStrategy;
}

function formatForStrategy(
  file: File,
  settings: CompressionSettings,
  strategy: CompressionStrategy
): OutputFormat {
  if (
    strategy === "png-optimize" ||
    strategy === "png-quantized" ||
    strategy === "png-encode-fallback"
  ) {
    return "png";
  }

  if (strategy === "webp-lossless" || strategy === "webp-lossy") {
    return "webp";
  }

  if (strategy === "avif-lossy") {
    return "avif";
  }

  return resolveOutputFormat(file, settings.format);
}

function createPendingVariant(
  file: File,
  task: CompressionTask,
  sourceFormat: OutputFormat | null,
  existingId?: string
): CompressionVariant {
  return {
    auto: task.auto ?? false,
    autoGenerated: task.autoGenerated,
    createdAt: Date.now(),
    format: formatForStrategy(file, task.settings, task.strategy),
    id: existingId ?? crypto.randomUUID(),
    presetId: task.presetId,
    progress: 5,
    settings: task.settings,
    signature: settingsSignature(task.settings, task.presetId, task.strategy),
    sizeDelta: null,
    sourceFormat,
    strategy: task.strategy,
    status: "processing",
  };
}

// Auto mode emits up to two candidates per file: a Safe pick that keeps the
// source format and its quality (the default download), and a Smaller pick in a
// modern format that we only *offer*. The user (or the size-comparison logic)
// decides which one wins — Auto never silently locks in a lossy conversion.
function buildAutoTasks(
  settings: CompressionSettings,
  presetId: string | null,
  autoGenerated: boolean,
  sourceFormat: OutputFormat | null
): CompressionTask[] {
  const base = { auto: true, autoGenerated, presetId } as const;
  const quality = settings.quality;
  const webpSmaller: CompressionTask = {
    ...base,
    settings: { ...settings, format: "webp", lossless: false, quality },
    strategy: "webp-lossy",
  };

  if (sourceFormat === "png") {
    return [
      {
        ...base,
        settings: {
          ...settings,
          format: "png",
          lossless: true,
          pngMode: "lossless",
          quality: 100,
        },
        strategy: "png-optimize",
      },
      webpSmaller,
    ];
  }

  if (sourceFormat === "jpeg") {
    return [
      {
        ...base,
        settings: { ...settings, format: "jpeg", lossless: false, quality },
        strategy: "same-format",
      },
      webpSmaller,
    ];
  }

  // WebP/AVIF are already efficient modern formats — just re-encode in place at
  // the chosen quality. If that can't beat the original, the original is kept.
  if (sourceFormat === "webp" || sourceFormat === "avif") {
    return [
      {
        ...base,
        settings: {
          ...settings,
          format: sourceFormat,
          lossless: false,
          quality,
        },
        strategy: sourceFormat === "webp" ? "webp-lossy" : "avif-lossy",
      },
    ];
  }

  return [
    {
      ...base,
      settings: { ...settings, format: "original" },
      strategy: "same-format",
    },
  ];
}

function buildCompressionTasks(
  file: File,
  settings: CompressionSettings,
  presetId: string | null,
  autoGenerated: boolean
): CompressionTask[] {
  const sourceFormat = formatFromFile(file);

  if (settings.format === "auto") {
    return buildAutoTasks(settings, presetId, autoGenerated, sourceFormat);
  }

  if (presetId === "keep-quality" && sourceFormat === "png") {
    return [
      {
        autoGenerated,
        presetId,
        settings: {
          format: "original",
          lossless: true,
          pngColors: 256,
          pngMode: "lossless",
          quality: 100,
        },
        strategy: "png-optimize",
      },
    ];
  }

  if (presetId === "smaller-file" && sourceFormat === "png") {
    return [
      {
        autoGenerated,
        presetId,
        settings: {
          format: "webp",
          lossless: false,
          pngColors: 256,
          pngMode: "lossless",
          quality: 82,
        },
        strategy: "webp-lossy",
      },
    ];
  }

  if (presetId === "compressed-png") {
    return [
      {
        autoGenerated,
        presetId,
        settings: {
          ...settings,
          format: "png",
          lossless: true,
          pngColors: settings.pngColors,
          pngMode: "compressed",
        },
        strategy: "png-quantized",
      },
    ];
  }

  if (presetId === "modern-web") {
    return [
      {
        autoGenerated,
        presetId,
        settings: {
          format: "webp",
          lossless: false,
          pngColors: 256,
          pngMode: "lossless",
          quality: 82,
        },
        strategy: "webp-lossy",
      },
    ];
  }

  if (sourceFormat === "png" && settings.format === "original") {
    return [
      {
        autoGenerated,
        presetId,
        settings: { ...settings, lossless: true, pngMode: "lossless" },
        strategy: "png-optimize",
      },
    ];
  }

  if (settings.format === "png") {
    return [
      {
        autoGenerated,
        presetId,
        settings: { ...settings, lossless: true },
        strategy:
          settings.pngMode === "compressed" ? "png-quantized" : "png-optimize",
      },
    ];
  }

  if (settings.format === "webp") {
    return [
      {
        autoGenerated,
        presetId,
        settings,
        strategy: settings.lossless ? "webp-lossless" : "webp-lossy",
      },
    ];
  }

  if (settings.format === "avif") {
    return [
      {
        autoGenerated,
        presetId,
        settings,
        strategy: "avif-lossy",
      },
    ];
  }

  return [
    {
      autoGenerated,
      presetId,
      settings,
      strategy: "same-format",
    },
  ];
}

function getBestVariantId(variants: CompressionVariant[]): string | null {
  const candidates = variants.filter(
    (
      variant
    ): variant is CompressionVariant & { output: Blob; sizeDelta: number } =>
      !!variant.output &&
      variant.sizeDelta !== null &&
      variant.sizeDelta < 0 &&
      variant.status !== "error"
  );

  if (!candidates.length) {
    return null;
  }

  candidates.sort((left, right) => left.output.size - right.output.size);
  return candidates[0]?.id ?? null;
}

// In Auto mode the default selection is the quality-safe candidate: the one
// that keeps the source format and is genuinely smaller than the original.
// Returns null when nothing same-format beats the original, so we keep it.
function getSafeVariantId(
  variants: CompressionVariant[],
  sourceFormat: OutputFormat | null
): string | null {
  if (!sourceFormat) {
    return null;
  }

  const candidates = variants.filter(
    (
      variant
    ): variant is CompressionVariant & { output: Blob; sizeDelta: number } =>
      !!variant.output &&
      variant.status !== "error" &&
      variant.sizeDelta !== null &&
      variant.sizeDelta < 0 &&
      variant.format === sourceFormat
  );

  if (!candidates.length) {
    return null;
  }

  candidates.sort((left, right) => left.output.size - right.output.size);
  return candidates[0]?.id ?? null;
}

function getJobStatus(variants: CompressionVariant[]): CompressionJobStatus {
  if (variants.some((variant) => variant.status === "processing")) {
    return "processing";
  }

  if (
    variants.some(
      (variant) =>
        variant.status === "done" || variant.status === "larger-than-original"
    )
  ) {
    return "done";
  }

  if (variants.some((variant) => variant.status === "error")) {
    return "error";
  }

  return "queued";
}

function updateVariantFromWorker(
  job: CompressionJob,
  variant: CompressionVariant,
  event: WorkerCompressResponse
): CompressionVariant {
  if (event.kind === "runtime-error") {
    if (event.variantId && variant.id !== event.variantId) {
      return variant;
    }

    if (variant.status !== "processing") {
      return variant;
    }

    return {
      ...variant,
      error: formatWorkerRuntimeIssue(event.error, event.detail),
      progress: 100,
      status: "error",
    };
  }

  if (variant.id !== event.variantId) {
    return variant;
  }

  if (event.kind === "progress") {
    return {
      ...variant,
      progress: Math.max(variant.progress, event.progress),
    };
  }

  if (!event.ok) {
    return {
      ...variant,
      error: event.error,
      progress: 100,
      status: "error",
    };
  }

  const sizeDelta = event.output.size - job.file.size;

  return {
    ...variant,
    autoGenerated: event.autoGenerated,
    format: event.format,
    note: event.note,
    output: event.output,
    outputName: event.outputName,
    progress: 100,
    sourceFormat: event.sourceFormat,
    strategy: event.strategy,
    sizeDelta,
    status: sizeDelta > 0 ? "larger-than-original" : "done",
  };
}

function applyWorkerEventToJob(
  job: CompressionJob,
  event: WorkerCompressResponse
): CompressionJob {
  if (event.kind === "runtime-error") {
    if (event.sourceId && job.id !== event.sourceId) {
      return job;
    }

    const error = formatWorkerRuntimeIssue(event.error, event.detail);
    const variants = job.variants.map((variant) =>
      updateVariantFromWorker(job, variant, event)
    );

    return {
      ...job,
      activeVariantId: job.activeVariantId,
      bestVariantId: getBestVariantId(variants),
      error,
      status:
        job.status === "processing" ||
        variants.some((variant) => variant.status === "error")
          ? "error"
          : job.status,
      variants,
    };
  }

  if (job.id !== event.sourceId) {
    return job;
  }

  // Ignore progress/results for Auto candidates that were superseded and pruned
  // on a re-run, so their stale completions can't disturb the current variants.
  if (!job.variants.some((variant) => variant.id === event.variantId)) {
    return job;
  }

  const variants = job.variants.map((variant) =>
    updateVariantFromWorker(job, variant, event)
  );
  const finishedVariant = variants.find(
    (variant) => variant.id === event.variantId
  );
  const sourceFormat = formatFromFile(job.file);
  const autoMode = variants.some((variant) => variant.auto);
  // bestVariantId tracks the absolute smallest (used to surface the "compress
  // more" suggestion). The auto-selected (active) variant is the quality-safe
  // pick in Auto mode, or the smallest otherwise.
  const nextBestVariantId = getBestVariantId(variants);
  const nextActiveCandidate = autoMode
    ? getSafeVariantId(variants, sourceFormat)
    : nextBestVariantId;
  // Keep the user's explicit pick (a clicked chip) and never move selection off
  // an errored variant.
  const activeVariantId =
    job.activeVariantPinned || finishedVariant?.status === "error"
      ? job.activeVariantId
      : nextActiveCandidate;

  return {
    ...job,
    activeVariantId,
    bestVariantId: nextBestVariantId,
    error:
      finishedVariant?.status === "error" ? finishedVariant.error : undefined,
    status: getJobStatus(variants),
    variants,
  };
}

function getVariantById(
  job: CompressionJob | undefined,
  variantId: string | null
) {
  if (!(job && variantId)) {
    return null;
  }

  return job.variants.find((variant) => variant.id === variantId) ?? null;
}

function getDownloadTarget(job: CompressionJob | undefined) {
  if (!job) {
    return null;
  }

  // activeVariantId is authoritative: the Safe pick in Auto mode, the result of
  // a manual apply, or whatever chip the user clicked. When it is null we keep
  // the original rather than a smaller conversion the user never opted into.
  const activeVariant = getVariantById(job, job.activeVariantId);
  if (activeVariant?.output && activeVariant.outputName) {
    return { blob: activeVariant.output, name: activeVariant.outputName };
  }

  return { blob: job.file, name: job.file.name };
}

export default function CompressorApp() {
  const [settings, setSettings] = useState<CompressionSettings>(
    () => loadSettings() ?? defaultSettings
  );
  const [activePresetId, setActivePresetId] = useState<string | null>(null);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [jobs, setJobs] = useState<CompressionJob[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [checkedIds, setCheckedIds] = useState<Set<string>>(new Set());
  const [globalError, setGlobalError] = useState("");
  const addFilesInputRef = useRef<HTMLInputElement>(null);
  const jobsRef = useRef<CompressionJob[]>([]);
  const workerRef = useRef<Worker | null>(null);
  const settingsRef = useRef(settings);

  useEffect(() => {
    settingsRef.current = settings;
  }, [settings]);

  useEffect(() => {
    jobsRef.current = jobs;
  }, [jobs]);

  const selectedJob = useMemo(
    () => jobs.find((job) => job.id === selectedId),
    [jobs, selectedId]
  );
  const selectedSourceFormat = useMemo(
    () => (selectedJob ? formatFromFile(selectedJob.file) : null),
    [selectedJob]
  );
  const fallbackSourceFormat = useMemo(
    () => (jobs[0] ? formatFromFile(jobs[0].file) : null),
    [jobs]
  );
  const hasJobs = jobs.length > 0;
  const hasCompleted = jobs.some((job) => job.status === "done");
  const isProcessing = jobs.some((job) => job.status === "processing");
  const allChecked = hasJobs && jobs.every((job) => checkedIds.has(job.id));
  const selectedCount = checkedIds.size;

  useEffect(() => {
    return () => {
      workerRef.current?.terminate();
      workerRef.current = null;
    };
  }, []);

  const ensureWorker = useCallback(() => {
    if (!workerRef.current) {
      workerRef.current = new Worker(
        new URL("../../lib/workers/compression.worker.ts", import.meta.url),
        { type: "module" }
      );
      workerRef.current.onmessage = (
        event: MessageEvent<WorkerCompressResponse>
      ) => {
        if (event.data.kind === "runtime-error") {
          const error = formatWorkerRuntimeIssue(
            event.data.error,
            event.data.detail
          );
          console.error("[Smol] Worker runtime error", event.data);
          setGlobalError(error);
        }

        setJobs((current) =>
          current.map((job) => applyWorkerEventToJob(job, event.data))
        );
      };
      workerRef.current.onerror = (event) => {
        const error = formatWorkerRuntimeIssue(
          event.message || genericWorkerFailureMessage,
          undefined,
          [
            event.filename ? `file: ${event.filename}` : null,
            event.lineno ? `line: ${event.lineno}` : null,
            event.colno ? `column: ${event.colno}` : null,
          ]
            .filter(Boolean)
            .join(", ") || undefined
        );

        console.error("[Smol] Worker onerror", event);
        setGlobalError(error);
        setJobs((current) => failProcessingJobs(current, error));
      };
      workerRef.current.onmessageerror = (event) => {
        const error =
          "The compression worker sent a message the app could not read.";

        console.error("[Smol] Worker onmessageerror", event);
        setGlobalError(error);
        setJobs((current) => failProcessingJobs(current, error));
      };
    }
    return workerRef.current;
  }, []);

  function queueCompression(
    sourceId: string,
    nextSettings: CompressionSettings,
    presetId: string | null,
    autoGenerated: boolean
  ) {
    const job = jobsRef.current.find((entry) => entry.id === sourceId);
    if (!job) {
      return;
    }

    const worker = ensureWorker();
    const sourceFormat = formatFromFile(job.file);
    const tasks = buildCompressionTasks(
      job.file,
      nextSettings,
      presetId,
      autoGenerated
    );
    const nextVariants = tasks.map((task) => {
      const existingVariant = job.variants.find(
        (variant) =>
          variant.signature ===
          settingsSignature(task.settings, task.presetId, task.strategy)
      );

      return createPendingVariant(
        job.file,
        task,
        sourceFormat,
        existingVariant?.id
      );
    });

    setJobs((current) =>
      current.map((entry) => {
        if (entry.id !== sourceId) {
          return entry;
        }

        const nextIds = new Set(nextVariants.map((variant) => variant.id));
        const variants = [
          // Keep manual/preset variants, but drop superseded Auto candidates so
          // the preview doesn't accumulate stale versions across re-runs.
          ...entry.variants.filter(
            (variant) => !(nextIds.has(variant.id) || variant.auto)
          ),
          ...nextVariants,
        ].sort((left, right) => left.createdAt - right.createdAt);

        return {
          ...entry,
          activeVariantId: null,
          activeVariantPinned: false,
          error: undefined,
          status: "processing",
          variants,
        };
      })
    );

    for (const [index, task] of tasks.entries()) {
      const nextVariant = nextVariants[index];
      if (!nextVariant) {
        continue;
      }

      worker.postMessage({
        autoGenerated: task.autoGenerated,
        file: job.file,
        presetId: task.presetId,
        settings: task.settings,
        sourceFormat,
        sourceId,
        strategy: task.strategy,
        variantId: nextVariant.id,
      });
    }
  }

  const addFiles = useCallback(
    (files: File[]) => {
      const selectedFiles = files.filter((file) =>
        file.type.startsWith("image/")
      );

      if (!selectedFiles.length) {
        setGlobalError("Drop in some images and Smol takes it from there.");
        return;
      }

      const currentSettings = settingsRef.current;
      saveSettings(currentSettings);
      setGlobalError("");
      const worker = ensureWorker();

      const nextJobs: CompressionJob[] = selectedFiles.map((file) => {
        const jobId = crypto.randomUUID();
        const sourceFormat = formatFromFile(file);
        const tasks = buildCompressionTasks(file, currentSettings, null, true);
        const variants = tasks.map((task) =>
          createPendingVariant(file, task, sourceFormat)
        );

        for (const [index, task] of tasks.entries()) {
          const variant = variants[index];
          if (!variant) {
            continue;
          }

          worker.postMessage({
            autoGenerated: task.autoGenerated,
            file,
            presetId: task.presetId,
            settings: task.settings,
            sourceFormat,
            sourceId: jobId,
            strategy: task.strategy,
            variantId: variant.id,
          });
        }

        return {
          activeVariantId: null,
          activeVariantPinned: false,
          bestVariantId: null,
          file,
          id: jobId,
          status: "processing",
          variants,
        };
      });

      const combined = [...jobsRef.current, ...nextJobs];
      setJobs(combined);
      setSelectedId((existing) => existing ?? combined[0]?.id ?? null);
    },
    [ensureWorker]
  );

  const fileInput = (
    <input
      accept="image/*"
      className="hidden"
      multiple
      onChange={(event) => {
        addFiles(Array.from(event.target.files ?? []));
        event.currentTarget.value = "";
      }}
      ref={addFilesInputRef}
      type="file"
    />
  );

  function handleSettingsChange(nextSettings: CompressionSettings) {
    setActivePresetId(null);
    setSettings(nextSettings);
    saveSettings(nextSettings);
  }

  function handleApplySettings(nextSettings: CompressionSettings) {
    handleSettingsChange(nextSettings);
    if (selectedJob) {
      queueCompression(selectedJob.id, nextSettings, null, false);
    }
  }

  function applyToAll(nextSettings: CompressionSettings) {
    handleSettingsChange(nextSettings);
    for (const job of targetedJobs(jobsRef.current)) {
      queueCompression(job.id, nextSettings, null, false);
    }
  }

  function handleQualityChange(quality: number) {
    handleSettingsChange({ ...settingsRef.current, quality });
  }

  function handleQualityCommit(quality: number) {
    const nextSettings = { ...settingsRef.current, quality };
    handleSettingsChange(nextSettings);
    for (const job of jobsRef.current) {
      queueCompression(job.id, nextSettings, null, false);
    }
  }

  function handleApplyPreset(presetId: string) {
    if (!selectedJob) {
      return;
    }

    const presetSettings =
      presets.find((entry) => entry.id === presetId)?.settings ??
      defaultSettings;
    setActivePresetId(presetId);
    setSettings(presetSettings);
    saveSettings(presetSettings);
    queueCompression(selectedJob.id, presetSettings, presetId, true);
  }

  function clearQueue() {
    if (isProcessing) {
      return;
    }
    setJobs([]);
    setSelectedId(null);
    setCheckedIds(new Set());
    setGlobalError("");
  }

  function toggleChecked(id: string) {
    setCheckedIds((current) => {
      const next = new Set(current);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  }

  function toggleAllChecked() {
    setCheckedIds((current) =>
      current.size === jobsRef.current.length
        ? new Set()
        : new Set(jobsRef.current.map((job) => job.id))
    );
  }

  // The targets for "download all" / "apply to all": the checked files when any
  // are selected, otherwise every file.
  function targetedJobs(source: CompressionJob[]) {
    return checkedIds.size > 0
      ? source.filter((job) => checkedIds.has(job.id))
      : source;
  }

  function openAddFilesPicker() {
    addFilesInputRef.current?.click();
  }

  function downloadSelected() {
    const target = getDownloadTarget(selectedJob);
    if (target) {
      downloadBlob(target.blob, target.name);
    }
  }

  async function downloadAllZip() {
    // Only zip finished jobs; skip anything still processing/queued so we never
    // bundle an original in place of an unfinished compression.
    const targets = targetedJobs(jobs).filter((job) => job.status === "done");
    if (!targets.length) {
      return;
    }

    try {
      const archive: Record<string, Uint8Array> = {};
      const usedNames = new Set<string>();

      for (const job of targets) {
        const target = getDownloadTarget(job);
        if (!target) {
          continue;
        }

        const safeName = uniqueName(target.name, usedNames);
        archive[safeName] = new Uint8Array(await target.blob.arrayBuffer());
      }

      const zipData = await new Promise<Uint8Array>((resolve, reject) => {
        zip(archive, { level: 6 }, (err, data) => {
          if (err) {
            reject(err);
            return;
          }
          resolve(data);
        });
      });
      const zipBuffer = Uint8Array.from(zipData).buffer;

      downloadBlob(
        new Blob([zipBuffer], { type: "application/zip" }),
        "smol.zip"
      );
    } catch (err) {
      setGlobalError(
        err instanceof Error ? err.message : "Could not put the zip together."
      );
    }
  }

  function setActiveVariant(sourceId: string, variantId: string | null) {
    setJobs((current) =>
      current.map((job) =>
        job.id === sourceId
          ? { ...job, activeVariantId: variantId, activeVariantPinned: true }
          : job
      )
    );
  }

  if (!hasJobs) {
    return (
      <div className="flex h-full min-h-0 flex-col overflow-hidden">
        <div className="flex flex-1 flex-col">
          <Dropzone onFiles={addFiles} />
        </div>
        {globalError && (
          <p className="border-[color:color-mix(in_oklab,var(--color-error)_30%,transparent)] border-t bg-[color:color-mix(in_oklab,var(--color-error)_12%,transparent)] px-4 py-2.5 text-center text-[0.88rem] text-[color:color-mix(in_oklab,var(--color-error)_72%,white_28%)]">
            {globalError}
          </p>
        )}
      </div>
    );
  }

  const toolbar = (
    <ToolbarControls
      hasCompleted={hasCompleted}
      hasJobs={hasJobs}
      hasSelection={!!selectedJob}
      isProcessing={isProcessing}
      onAddFiles={openAddFilesPicker}
      onClear={clearQueue}
      onDownloadSelected={downloadSelected}
      onDownloadZip={downloadAllZip}
      onOpenSettings={() => setSettingsOpen(true)}
      onQualityChange={handleQualityChange}
      onQualityCommit={handleQualityCommit}
      selectedCount={selectedCount}
      settings={settings}
    />
  );

  const settingsDialog = (
    <SettingsDialog
      activePresetId={activePresetId}
      hasJobs={hasJobs}
      hasSelection={!!selectedJob}
      isProcessing={isProcessing}
      onApplyAll={applyToAll}
      onApplyPreset={handleApplyPreset}
      onApplySelected={handleApplySettings}
      onChange={handleSettingsChange}
      onClose={() => setSettingsOpen(false)}
      open={settingsOpen}
      selectedCount={selectedCount}
      settings={settings}
      sourceFormat={selectedSourceFormat ?? fallbackSourceFormat}
    />
  );

  return (
    <div className="flex h-full min-h-0 flex-col overflow-hidden">
      <div className="flex min-h-0 flex-1 flex-col overflow-hidden md:flex-row">
        <CompressionList
          allChecked={allChecked}
          checkedIds={checkedIds}
          jobs={jobs}
          onSelect={setSelectedId}
          onToggleAll={toggleAllChecked}
          onToggleChecked={toggleChecked}
          selectedId={selectedId}
        />
        <div className="flex min-w-0 flex-1 flex-col overflow-hidden">
          <PreviewPanel
            job={selectedJob}
            onSelectVariant={(variantId) => {
              if (selectedJob) {
                setActiveVariant(selectedJob.id, variantId);
              }
            }}
          />
        </div>
      </div>

      {globalError && (
        <p className="border-[color:color-mix(in_oklab,var(--color-error)_30%,transparent)] border-t bg-[color:color-mix(in_oklab,var(--color-error)_12%,transparent)] px-4 py-2.5 text-center text-[0.88rem] text-[color:color-mix(in_oklab,var(--color-error)_72%,white_28%)]">
          {globalError}
        </p>
      )}

      {fileInput}
      {toolbar}
      {settingsDialog}
    </div>
  );
}
